version: "3.2"

services:
  gateway-proxy:
    image: smartspaces/gateway-proxy:${TAG:-latest}
    restart: always
    ports:
      - "5000:80"
    networks:
      - private-network
    environment:
      - "USER_SERVICE_URL=https://user-service.ecampuslearning.com"

  user-service:
    image: smartspaces/user-service:${TAG:-latest}
    restart: always
    networks:
      - private-network
    environment:
      - "MONGO_URL=mongodb://mongo"

  item-service:
    image: smartspaces/item-service:${TAG:-latest}
    restart: always
    networks:
      - private-network
    environment:
      - "MONGO_URL=mongodb://mongo"
      - "INVENTORY_SERVICE_URL=https://inventory-service.ecampuslearning.com

  inventory-service:
    image: smartspaces/inventory-service:${TAG:-latest}
    restart: always
    networks:
      - private-network
    environment:
      - "MONGO_URL=mongodb://mongo"

  mongo:
    image: mongo:${MONGO_TAG-latest}
    volumes:
      - ./data:/data/db
    networks:
      - private-network

networks:
  private-network:
